# Generated by Django 4.0.4 on 2022-05-09 10:44

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('findimage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('gallery_name', models.CharField(max_length=200)),
                ('gallery_img', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['READER'], gdstorage.storage.GoogleDrivePermissionType['USER'], 'findimage123@gmail.com'),)), upload_to='gallery/')),
            ],
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
